---

# Install additional  nice to have packges

- name: apt install initial packages
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
    
- name: Add modules
  lineinfile: 
    dest: /etc/modules
    line: "{{ item }}"
  loop: "{{ modules_required }}"
  register: modules_req
...
