---
# My Raspberry Pi and other Debian hosts

all:
    children:
        minisystem:
            hosts:
                minisys:
                azure:
                dt:
        webserver:
            hosts:
                minisys:
                azure:
                dt:
...
