---
# My Raspberry Pi and other Debian hosts

all:
    children:
        vserver:
            hosts:
                virtsvr:
                rootsvr:
                azure:
        pc:
            hosts:
                dt-thomas:   # My desktop
                lt-thomas:   # My laptop
        gateways:
            hosts:

...
