---
# My Raspberry Pi and other Debian hosts

all:
    children:
        vserver:
            hosts:
                virtsvr:
                rootsvr:
                azure:
        pc:
            hosts:
                tux-dt:   # My desktop
                tux-lt:   # My laptop
        gateways:
            hosts:

...
