---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-06-23

- name: Delete servers and pool from ntp.conf
  lineinfile:
    dest: /etc/ntp.conf
    regexp: '(^pool|^server) .*'
    state: absent
  when: timeservers is defined or timepool is defined

- name: Insert pool into /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    line: "pool {{ item }}"
  loop: "{{ ntp_server.pools[timepool] | list }}"
  register: ntppool
  when: timepool is defined and ntp_server.pools[timepool] is defined

- name: Insert server into /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ item }} iburst"
  loop: "{{ ntp_server.server[timeservers] | list }}"
  register: ntpsvr
  when: timeservers is defined and ntp_server.server[timeservers] is defined
  
- name: Restart ntp
  service:
    name: ntp.service
    state: restarted
  when: ( ntppool is changed ) or ( ntpsvr is changed )
...
