---
ansible_host: pi-e.dyn.byggvir.de
ansible_user: pi

gre:
  ekir:
    tunnel:
        remote: 79.210.203.74
        local:  '{{ ansible_default_ipv4.address }}'
        netmask: 255.255.255.254
        mtu: 1400
        ttl: 64
    dev: gre-ekir
    address: 10.0.100.2
    daddress: 10.0.100.1
    network: 10.0.100.0/24
...
