---

- name: Install minimal system requirements for ansible
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - include_role:
        name: minimalsystem

- name: Install NTP
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - include_role:
        name: ntpserver

- name: Install samba
  hosts: samba
  gather_facts: false
  become: yes
  tasks:
    - include_role:
        name: samba

- name: Install webserver
  hosts: webserver
  gather_facts: false
  become: yes
  tasks:
    - include_role:
        name: webserver



...
